export default {
    SET_ROUND_TRIP : "SET_ROUND_TRIP",
    SET_CLASS : "SET_CLASS",
    SET_NUMBER_CUSTOMER : "SET_NUMBER_CUSTOMER",
    SET_WHERE_FROM : "SET_WHERE_FROM",
    SET_WHERE_TO : "SET_WHERE_TO",
}